on: [push]
jobs: 
  my-job-v2-rc:
    name: Run Tests V2
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0

      # Run MATLAB build tool
      - name: Run build
        uses: matlab-actions/run-build@v2-rc0
